## 인터엑스 프로젝트 추출 데이터 정제 작업

In [1]:
#라이브러리 import

import pandas as pd
from openpyxl import load_workbook
import os
import re
from collections import Counter

dir_path = os.getcwd()
dir_path = os.path.join(dir_path, "file")
print(dir_path)

c:\Users\PC\Desktop\git_repo\ML-DL-Training\Data_preprocess\workspace\file

In [8]:
# 파일 경로와 읽을 열 이름
file_name = "Project_data.xlsx"
file_path = os.path.join(dir_path,file_name)  
column_name = 'A'  

# 엑셀 파일 읽기
word_sheet = pd.read_excel(file_path, sheet_name='Sheet1', usecols=column_name)
abb_sheet = pd.read_excel(file_path, sheet_name='Sheet2', usecols=column_name)

word_sheet = word_sheet.applymap(lambda s: s.lower())
abb_sheet = abb_sheet.applymap(lambda s: s.upper())

C:\Users\PC\AppData\Local\Temp\ipykernel_16016\2354502705.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  word_sheet = word_sheet.applymap(lambda s: s.lower())
C:\Users\PC\AppData\Local\Temp\ipykernel_16016\2354502705.py:11: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  abb_sheet = abb_sheet.applymap(lambda s: s.upper())

In [14]:
word_sheet

             Word
0        handover
1         ability
2    acceleration
3          access
4        accident
..            ...
645    extraction
646          load
647       loading
648          turn
649        return

[650 rows x 1 columns]

In [15]:
abb_sheet

   Unnamed: 0
0       CCRUU
1          CE
2        ECAD
3          EO
4        FMCG
5         KPI
6        MCAD
7         MGT
8          NC
9        MTBF
10        NEG
11        OEE
12      OPCUA
13       PFHD
14         PH
15        RMS
16        RPM
17        SPC
18       RFID
19     O-RING
20       RFID
21    CP-TRIP

In [16]:
# 결과 엑셀 시트에 분할 저장
result_file_path = os.path.join(dir_path,'interX_Data.xlsx')
with pd.ExcelWriter(result_file_path) as writer:
    word_sheet.to_excel(writer, sheet_name='Sheet1', index=False)
    abb_sheet.to_excel(writer, sheet_name='Sheet2', index=False)